### ISSUE TITLE
Editor immediately crashes after clicking

### ISSUE THREAD

**Issue by Mikusch** [Hexer10/SPCode#40]
Stack Trace:
```
1
Section: SPCODE MAIN
.NET Version: 4.0.30319.42000
OS: Microsoft Windows NT 6.2.9200.0
64 bit OS: TRUE
64 bit mode: TRUE
Dir: C:\Users\Mikusch\AppData\Roaming\spcode
Working Set: 173116 kb
Installed UI Culture: en-US
Current UI Culture: en-GB
Current Culture: en-DE

Exception 1
Message:
parsing "\bADMFLAG_BAN\b|\bADMFLAG_CHANGEMAP\b|\bADMFLAG_CHAT\b|\bADMFLAG_CHEATS\b|\bADMFLAG_CONFIG\b|\bADMFLAG_CONVARS\b|\bADMFLAG_CUSTOM1\b|\bADMFLAG_CUSTOM2\b|\bADMFLAG_CUSTOM3\b|\bADMFLAG_CUSTOM4\b|\bADMFLAG_CUSTOM5\b|\bADMFLAG_CUSTOM6\b|\bADMFLAG_GENERIC\b|\bADMFLAG_KICK\b|\bADMFLAG_PASSWORD\b|\bADMFLAG_RCON\b|\bADMFLAG_RESERVATION\b|\bADMFLAG_ROOT\b|\bADMFLAG_SLAY\b|\bADMFLAG_UNBAN\b|\bADMFLAG_VOTE\b|\bADMINMENU_PLAYERCOMMANDS\b|\bADMINMENU_SERVERCOMMANDS\b|\bADMINMENU_VOTINGCOMMANDS\b|\bALL_VISIBLE_CONTENTS\b|\bATTACHMENTPOLICY_MODEL\b|\bAUTHMETHOD_IP\b|\bAUTHMETHOD_NAME\b|\bAUTHMETHOD_STEAM\b|\bAVERAGE_JUMPTIME\b|\bAdminFlags_TOTAL\b|\bBANFLAG_AUTHID\b|\bBANFLAG_AUTO\b|\bBANFLAG_IP\b|\bBANFLAG_NOKICK\b|\bCINIT(%1,%2,%3)\b|\bCOLOR_ALICEBLUE\b|\bCOLOR_ALLIES\b|\bCOLOR_ANCIENT\b|\bCOLOR_ANTIQUEWHITE\b|\bCOLOR_AQUA\b|\bCOLOR_AQUAMARINE\b|\bCOLOR_ARCANA\b|\bCOLOR_AXIS\b|\bCOLOR_AZURE\b|\bCOLOR_BEIGE\b|\bCOLOR_BISQUE\b|\bCOLOR_BLACK\b|\bCOLOR_BLANCHEDALMOND\b|\bCOLOR_BLUEVIOLET\b|\bCOLOR_BROWN\b|\bCOLOR_BURLYWOOD..." - Not enough )'s.
Stacktrace:
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at System.Text.RegularExpressions.Regex..ctor(String pattern)
   at SPCode.UI.Components.AeonEditorHighlighting.get_MainRuleSet()
   at ICSharpCode.AvalonEdit.Highlighting.DocumentHighlighter..ctor(TextDocument document, IHighlightingDefinition definition)
   at ICSharpCode.AvalonEdit.Highlighting.HighlightingColorizer.CreateHighlighter(TextView textView, TextDocument document)
   at ICSharpCode.AvalonEdit.Highlighting.HighlightingColorizer.RegisterServices(TextView textView)
   at ICSharpCode.AvalonEdit.Rendering.TextView.LineTransformer_Added(IVisualLineTransformer lineTransformer)
   at ICSharpCode.AvalonEdit.Utils.ObserveAddRemoveCollection`1.InsertItem(Int32 index, T item)
   at ICSharpCode.AvalonEdit.TextEditor.OnSyntaxHighlightingChanged(IHighlightingDefinition newValue)
   at ICSharpCode.AvalonEdit.TextEditor.OnSyntaxHighlightingChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at SPCode.UI.Components.EditorElement.Caret_PositionChanged(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at ICSharpCode.AvalonEdit.Editing.Caret.RaisePositionChanged()
   at ICSharpCode.AvalonEdit.Editing.Caret.set_Position(TextViewPosition value)
   at ICSharpCode.AvalonEdit.Editing.SelectionMouseHandler.SetCaretOffsetToMousePosition(MouseEventArgs e, ISegment allowedSegment)
   at ICSharpCode.AvalonEdit.Editing.SelectionMouseHandler.textArea_MouseLeftButtonDown(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at SPCode.Program.Main(String[] args)
Source:
System
HResult Code:
-2147024809
Helplink:
null
Targetsite Name:
ScanRegex
```

**Comment by Hexer10** [comment]
I'm sorry, this is gonna be fixed in the next couple of hours
